# Module: nginx
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.9/metricbeat-module-nginx.html

- module: nginx
  #metricsets:
  #  - stubstatus
  period: 10s

  # Nginx hosts
  hosts: ["http://2z.v.show:92/nginx-status"]

  # Path to server status. Default server-status
  #server_status_path: "server-status"

  #username: "user"
  #password: "secret"
